### ISSUE TITLE
Crash when making world

### ISSUE THREAD

**Issue by t0mtee** [Apollointhehouse/BetterSpawnLocation#1]
```
[16:08:24] [Client-Main/ERROR] (FabricLoader/Mixin) Mixin apply for mod better_spawn_location failed betterspawnlocation.mixins.json:WorldTypeOverworldMixin from mod better_spawn_location -> net.minecraft.core.world.type.WorldTypeOverworld: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Cannot handle IASTORE opcode (0x4F) in class initialiser [ -> MAIN Applicator Phase -> betterspawnlocation.mixins.json:WorldTypeOverworldMixin from mod better_spawn_location -> Apply Initialisers]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Cannot handle IASTORE opcode (0x4F) in class initialiser [ -> MAIN Applicator Phase -> betterspawnlocation.mixins.json:WorldTypeOverworldMixin from mod better_spawn_location -> Apply Initialisers]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.getInitialiser(MixinApplicatorStandard.java:927) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInitialisers(MixinApplicatorStandard.java:784) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.14.19-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.14.19-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.14.19-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) [fabric-loader-0.14.19-babric.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_382]
	at java.lang.ClassLoader.defineClass1(Native Method) [?:1.8.0_382]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) [?:1.8.0_382]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) [?:1.8.0_382]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) [fabric-loader-0.14.19-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) [fabric-loader-0.14.19-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.14.19-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) [fabric-loader-0.14.19-babric.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_382]
	at net.minecraft.client.gui.GuiCreateWorld.<init>(GuiCreateWorld.java:40) [minecraft.jar:?]
	at net.minecraft.client.gui.GuiSelectWorld.buttonPressed(GuiSelectWorld.java:148) [minecraft.jar:?]
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:88) [minecraft.jar:?]
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:137) [minecraft.jar:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1163) [minecraft.jar:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:695) [minecraft.jar:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_382]
[16:08:24] [Client-Main] java.lang.RuntimeException: Mixin transformation of net.minecraft.core.world.type.WorldTypeOverworld failed
[16:08:24] [Client-Main] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
[16:08:24] [Client-Main] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
[16:08:24] [Client-Main] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
[16:08:24] [Client-Main] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
[16:08:24] [Client-Main] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[16:08:24] [Client-Main] 	at java.lang.ClassLoader.defineClass1(Native Method)
[16:08:24] [Client-Main] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
[16:08:24] [Client-Main] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[16:08:24] [Client-Main] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153)
[16:08:24] [Client-Main] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
[16:08:24] [Client-Main] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
[16:08:24] [Client-Main] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
[16:08:24] [Client-Main] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[16:08:24] [Client-Main] 	at net.minecraft.client.gui.GuiCreateWorld.<init>(GuiCreateWorld.java:40)
[16:08:24] [Client-Main] 	at net.minecraft.client.gui.GuiSelectWorld.buttonPressed(GuiSelectWorld.java:148)
[16:08:24] [Client-Main] 	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:88)
[16:08:24] [Client-Main] 	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:137)
[16:08:24] [Client-Main] 	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1163)
[16:08:24] [Client-Main] 	at net.minecraft.client.Minecraft.run(Minecraft.java:695)
[16:08:24] [Client-Main] 	at java.lang.Thread.run(Thread.java:750)
[16:08:24] [Client-Main] Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[16:08:24] [Client-Main] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[16:08:24] [Client-Main] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
[16:08:24] [Client-Main] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
[16:08:24] [Client-Main] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
[16:08:24] [Client-Main] 	... 19 more
[16:08:24] [Client-Main] Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [betterspawnlocation.mixins.json:WorldTypeOverworldMixin from mod better_spawn_location] from phase [DEFAULT] in config [betterspawnlocation.mixins.json] FAILED during APPLY
[16:08:24] [Client-Main] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
[16:08:24] [Client-Main] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
[16:08:24] [Client-Main] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
[16:08:24] [Client-Main] 	... 22 more
[16:08:24] [Client-Main] Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Cannot handle IASTORE opcode (0x4F) in class initialiser [ -> MAIN Applicator Phase -> betterspawnlocation.mixins.json:WorldTypeOverworldMixin from mod better_spawn_location -> Apply Initialisers]
[16:08:24] [Client-Main] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.getInitialiser(MixinApplicatorStandard.java:927)
[16:08:24] [Client-Main] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInitialisers(MixinApplicatorStandard.java:784)
[16:08:24] [Client-Main] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
[16:08:24] [Client-Main] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[16:08:24] [Client-Main] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
[16:08:24] [Client-Main] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
[16:08:24] [Client-Main] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[16:08:24] [Client-Main] 	... 22 more
```

**Comment by Apollointhehouse** [comment]
Fixed it https://github.com/Apollointhehouse/BetterSpawnLocation/releases/tag/v1.0.1
